---
version: "2.9"
name: MySimple Scheduler
description: Simple timer on weekly base
slug: simplescheduler
url: https://github.com/ye0534143454/MySimpleScheduler
codenotary: notary@home-assistant.io
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
homeassistant_api: true
ingress: true
panel_admin: false
panel_title: Scheduler
panel_icon: mdi:calendar-clock
map:
  - share:rw
