---
version: "2.7.2"
name: Simple Scheduler
description: Simple timer on weekly base
def load_json_schedulers():
    ss = []
    os.chdir(simpleschedulerconf.json_folder)
    for folder in os.listdir(simpleschedulerconf.json_folder):
        if os.path.isdir(folder):
            for file in glob.glob(os.path.join(folder, '*.json')):
                with open(file, 'r') as read_file:
                    try:
                        ss.append(json.load(read_file))
                    except:
                        printlog('ERROR: scheduler file %s is corrupted' % file)
    return ss

init: false
homeassistant_api: true
ingress: true
panel_admin: false
panel_title: Scheduler
panel_icon: mdi:calendar-clock
map:
  - share:rw

def update_json_file(object_id, field_name, field_value, folder=''):
    if folder:
        folder_path = os.path.join(simpleschedulerconf.json_folder, folder)
        if not os.path.exists(folder_path):
            os.makedirs(folder_path)
        file = os.path.join(folder_path, object_id + '.json')
    else:
        file = simpleschedulerconf.json_folder + object_id + '.json'
    try:
        if os.path.exists(file):
            with open(file, 'r') as jsonFile:
                data = json.load(jsonFile)
            data[field_name] = field_value
            with open(file, 'w') as jsonFile:
                json.dump(data, jsonFile)
    except:
        printlog('ERROR: Unable to update JSON file')
    return True

<form action='/savescheduler' method='POST'>
    <!-- Additional form fields -->
    <label for='schedulerfolder'>בחר תיקיה:</label>
    <select name='schedulerfolder' id='schedulerfolder'>
        <option value='daily'>יומי</option>
        <option value='weekly'>שבועי</option>
        <option value='recurring'>חוזר</option>
    </select>
</form>


@app.route('/savescheduler', methods=['POST'])
def webserver_save_scheduler():
    sid = request.form.get('id')
    folder = request.form.get('schedulerfolder')
    field_name = 'your_field_name'
    field_value = 'your_field_value'
    update_json_file(sid, field_name, field_value, folder)
    return redirect('main')
