---
version: "2.7"
name: Simple Scheduler
description: Simple timer on weekly base
slug: simplescheduler
url: https://github.com/ye0534143454/MySimpleScheduler
codenotary: notary@home-assistant.io
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
image: ghcr.io/ye0534143454/MySimpleScheduler/{arch}
init: false
homeassistant_api: true
ingress: true
panel_admin: false
panel_title: Scheduler
panel_icon: mdi:calendar-clock
map:
  - share:rw
